services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432:5432

  backend:
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URI_LOCAL: ${DATABASE_URI_LOCAL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      TOKEN_ALGORITHM: ${TOKEN_ALGORITHM}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
